s = 'ATGCAGCAGCCGCAGCCGCAGGGGCAGCAGCAGCCGGGGCCGGGGCAGCAGCTGGGGGGCCAGGGGGCGG'
s2 = 'CGCCGGGGGCCGGGGGCGGCCCAGGGGGGGGCCCGGGGCCGGGGCCCTGCCTGAGGCGAGAGCTGAAGCT'
s3 = 'GCTCGAGTCCATCTTCCACCGCGGCCACGAGCGCTTCCGCATTGCCAGCGCCTGCCTGGACGAGCTGAGC'
s4 = 'TGCGAGTTCCTGCTGGCTGGGGCCGGAGGGGCCGGGGCGGGGGCCGCGCCCGGACCGCATCTCCCCCCAC'
s5 = 'GGGGGTCGGTGCCTGGGGATCCTGTCCGCATCCACTGCAACATCACGGAGTCATACCCTGCTGTGCCCCC'
s6 = 'CATCTGGTCGGTGGAGTCTGATGACCCTAACTTGGCTGCTGTCTTGGAGAGGCTGGTGGACATAAAGAAA'
s7 = 'GGGAATACTCTGCTATTGCAGCATCTGAAGAGGATCATCTCCGACCTGTGTAAACTCTATAACCTCCCTC'
s8 = 'AGCATCCAGATGTGGAGATGCTGGATCAACCCTTGCCAGCAGAGCAGTGCACACAGGAAGACGTGTCTTC'
s9 = 'AGAAGATGAAGATGAGGAGATGCCTGAGGACACAGAAGACTTAGATCACTATGAAATGAAAGAGGAAGAG'
s10 = 'CCAGCTGAGGGCAAGAAATCTGAAGATGATGGCATTGGAAAAGAAAACTTGGCCATCCTAGAGAAAATTA'
s11 = 'AAAAGAACCAGAGGCAAGATTACTTAAATGGTGCAGTGTCTGGCTCGGTGCAGGCCACTGACCGGCTGAT'
s12 = 'GAAGGAGCTCAGGGATATATACCGATCACAGAGTTTCAAAGGCGGAAACTATGCAGTCGAACTCGTGAAT'
s13 = 'CGACAGTCTGTATGATTGGAATGTCAAACTCCTCAAAGTTGACCAGGACAGCGCTTTGCACAACGATCTCC'
s14 = 'AGATCCTCAAAGAGAAAGAAGGAGCCGACTTCATTCTACTTAACTTTTCCTTTAAAGATAACTTTCCCTT'
s15 = 'TGACCCACCATTTGTCAGGGTTGTGTCTCCAGTCCTCTCTGGAGGGTATGTTCTGGGCGGAGGGGCCATCTGCATGGAACTTCTCACCAAACAGGGCTGGAGCAGTGCCTACTCCATAGAGTCAGTGATCATGCAGATCAGTGCCACACTGGTGAAGGGGAAAGCACGAGTGCAGTTTGGAGCCAACAAATCTCAATACAGTCTGACAAGAGCACAGCAGTCCTACAAGTCCTTGGTGCAGATCCACGAAAAAAACGGCTGGTACACACCCCCAAAAGAAGACGGCTAA'

seq = s + s2 + s3 + s4 + s5 + s6 + s7 + s8 + s9 + s10 + s11 + s12 + s13 + s14 + s15

print(len(seq))

count = 0
for i in range(len(seq) - 1):
    if seq[i] == 'C' and seq[i+1] == 'G':
        count += 1

print (count)